apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    component: db
  ports:
    - port: 3306        # Service port (exposed internally)
      targetPort: 3306  # Container port (MySQL)