version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-storage:/var/lib/mysql

  app-server:
    container_name: spring-app
    image: spring-library-app
    build:
      context: .
    ports:
      - "8181:8181"
    environment:
      SPRING_PROFILES_ACTIVE: mysql
    depends_on:
      - db
    restart: always

  web-client:
    container_name: react-client
    image: library-ui
    build:
      context: ../frontend
    ports:
      - "3001:8080"
    depends_on:
      - app-server
    restart: always

volumes:
  db-storage:
