name: Docker Build & Publish Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  container-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Spring Boot Backend
        uses: docker/build-push-action@v5
        with:
          context: ./library
          file: ./library/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/libapp-backend:latest

      - name: Build & Push React Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/libapp-ui:latest
